name: Deploy GitHub Pages

on:
  push:
    branches:
      - main # Trigger this workflow on push to the 'main' branch
  workflow_dispatch: # Allow manual triggering of this workflow

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Check out the repository
        uses: actions/checkout@v4

      # Step 2: Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2 # Replace with your desired Ruby version

      # Step 3: Install Bundler and Dependencies
      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      # Step 4: Build the site using Jekyll
      - name: Build the site
        run: |
          JEKYLL_ENV=production bundle exec jekyll build

      # Step 5: Upload the site artifact for GitHub Pages
      - name: Upload Artifact for Pages
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./_site # Specify the site build output directory

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      # Step 6: Deploy the site to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
